Transform: AWS::Serverless-2016-10-31
Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub
        - ${ResourceName} From Stack ${AWS::StackName}
        - ResourceName: Api
      StageName: Prod
      DefinitionBody:
        openapi: '3.0'
        info: {}
        paths:
          /:
            get:
              responses: {}
      EndpointConfiguration: REGIONAL
      TracingEnabled: true
  orderprocessor:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: orderprocessor
      CodeUri: src/orderprocessor
      Handler: handler.handler
      Runtime: python3.12
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Environment:
        Variables:
          API_API_URL: !Sub https://${Api}.execute-api.${AWS::Region}.amazonaws.com/${Api.Stage}
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - execute-api:Invoke
              Resource:
                - !Sub arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${Api}/${Api.Stage}/*
      Events:
        OrderEventsTopic:
          Type: SNS
          Properties:
            Topic: !Ref OrderEventsTopic
            Region: !Select
              - 3
              - !Split
                - ':'
                - !Ref OrderEventsTopic
  orderprocessorLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${orderprocessor}
  OrderEventsTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !GetAtt EmailQueue.Arn
          Protocol: sqs
        - Endpoint: !GetAtt paymentQueue.Arn
          Protocol: sqs
        - Endpoint: !GetAtt InventoryQueue.Arn
          Protocol: sqs
  paymentQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 345600
  EmailQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 345600
  InventoryQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 345600
  OrderEventsTopicToEmailQueueConnector:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Resource: !GetAtt EmailQueue.Arn
            Action: sqs:SendMessage
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref OrderEventsTopic
        Version: '2012-10-17'
      Queues:
        - !Ref EmailQueue
  OrderEventsTopicTopaymentQueueConnector:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Resource: !GetAtt paymentQueue.Arn
            Action: sqs:SendMessage
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref OrderEventsTopic
        Version: '2012-10-17'
      Queues:
        - !Ref paymentQueue
  OrderEventsTopicToInventoryQueueConnector:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Resource: !GetAtt InventoryQueue.Arn
            Action: sqs:SendMessage
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref OrderEventsTopic
        Version: '2012-10-17'
      Queues:
        - !Ref InventoryQueue
  Processpayment:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: Processpayment
      CodeUri: src/Function
      Handler: handler.handler
      Runtime: python3.12
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Environment:
        Variables:
          PAYMENTQUEUE_QUEUE_NAME: !GetAtt paymentQueue.QueueName
          PAYMENTQUEUE_QUEUE_ARN: !GetAtt paymentQueue.Arn
          PAYMENTQUEUE_QUEUE_URL: !Ref paymentQueue
          ORDERSTABLE_TABLE_NAME: !Ref ordersTable
          ORDERSTABLE_TABLE_ARN: !GetAtt ordersTable.Arn
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt paymentQueue.QueueName
        - DynamoDBCrudPolicy:
            TableName: !Ref ordersTable
  ProcesspaymentLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${Processpayment}
  SendEmail:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: SendEmail
      CodeUri: src/Function2
      Handler: handler.handler
      Runtime: python3.12
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Environment:
        Variables:
          EMAILQUEUE_QUEUE_NAME: !GetAtt EmailQueue.QueueName
          EMAILQUEUE_QUEUE_ARN: !GetAtt EmailQueue.Arn
          EMAILQUEUE_QUEUE_URL: !Ref EmailQueue
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt EmailQueue.QueueName
  SendEmailLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${SendEmail}
  UpdateInventory:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: UpdateInventory
      CodeUri: src/Function2
      Handler: handler.handler
      Runtime: python3.12
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Environment:
        Variables:
          INVENTORYQUEUE_QUEUE_NAME: !GetAtt InventoryQueue.QueueName
          INVENTORYQUEUE_QUEUE_ARN: !GetAtt InventoryQueue.Arn
          INVENTORYQUEUE_QUEUE_URL: !Ref InventoryQueue
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt InventoryQueue.QueueName
  UpdateInventoryLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${UpdateInventory}
  ordersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES